# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d486367d63ea93a4ade92965973148498d893b7cb7661a68fd3478f70e3652be4306c25247c1e5af54ed837b397581816844f2bac0f7b37a799bb91e6f49e66e

test:
  secret_key_base: 5ac2d659827946d827585e07ff5ec7a5fcb25bee0c1e5397be0d548f71c0509f2e31633b1d9ba8bcdd83c4401f70de4cb25fd1606e0f0b00612eea15480de415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
